### ISSUE TITLE
ValueError - time data does not match format

### ISSUE THREAD

**Issue by danieljuschus** [cgoillot/GPX_Correct#1]
I'm not sure why this happens, but I just tried running the program with a .gpx file from Runtastic and I get the following error message:

`ValueError: time data '2016-12-12T15:31:57Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'`

Changing line 94 into:

`t.append(datetime.strptime(elem2.text, '%Y-%m-%dT%H:%M:%SZ'))` 

seems to work. Is that a good fix?

**Comment by danieljuschus** [comment]
Also, I'm very new to github. Should I create a branch with the fix myself and then make a pull request?

**Comment by cgoillot** [comment]
From my experience, format is sometime "%Y-%m-%dT%H:%M:%SZ" and sometime "%Y-%m-%dT%H:%M:%S.%fZ"
I have included a try - except close that should solve the issue.
